export const POPULATE_MENU = 'POPULATE_MENU'
export const HIGHLIGHT_MENU = 'HIGHLIGHT_MENU'
export const REQUEST_MENU = 'REQUEST_MENU'
export const FORM_FACTOR = 'FORM_FACTOR'
export const SET_ACTIVE_PRODUCT = 'SET_ACTIVE_PRODUCT'
export const FETCH_POSTS = 'FETCH_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';

export const FETCH_NEWSPOSTS = 'FETCH_NEWSPOSTS';
export const RECEIVE_NEWSPOSTS = 'RECEIVE_NEWSPOSTS';
export const REQUEST_NEWSPOSTS = 'REQUEST_NEWSPOSTS';
export const POPULATE_NEWSPOSTS = 'POPULATE_NEWSPOSTS';